# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

charset: "UTF-8"
session: Storable
session_expires: 8 hours

### In case application is not on the root of domain
#base_url: "admin/"

# Template engine for front page
template: "template_toolkit"

# include timestamp in log format
logger_format: "%t [%P] %L @%D> %m in %f l. %l"

engines:
    JSON:
        allow_blessed:   '1'
        canonical:       '1'
        convert_blessed: '1'

plugins:
  Ajax:
    content_type: 'application/json'

# Sample configuration for authentication with Dancer::Plugin::Auth::Extensible
  Auth::Extensible:
    disable_roles: 0
    no_login_handler: 1
    login_page: /login
    logout_page: /logout
    denied_page: /login/denied
    no_default_pages: 1
    no_api_change_warning: 1
    realms:
      config:
        provider: Config
        users:
          - user: admin
            pass: 
            roles: [superadmin]
            
### Sample configuration with users in DB               
#      users:
#        provider: 'DBIC'
#        db_connection_name: 'default'
#        users_resultset: User
#        roles_relationship: roles
#        role_column: name
#        username_column: username
#        password_column: password
#        password_check: check_password

# Use different name to avoid conflicts in case
# we share domain with another Dancer application
session_name: tedit.session

TableEditor:
  dropdown_threshold: 300
  page_size: 10
  primary_key_delimiter: "_"
  page_sizes: [10, 20, 50, 100]
  full: [superadmin]

